#include <gtest/gtest.h>
#include "sql_parser/parser.h"
#include "sql_parser/emitter.h"
#include "sql_parser/parameterize.h"
#include "sql_engine/plan_builder.h"
#include <cstring>
#include <string>
using namespace sql_parser;

static const char* const table_constraint_positive[] = {
    "CREATE TABLE t (a int, CONSTRAINT ex EXCLUDE USING gist (a WITH =))",
    "CREATE TABLE t (a text, b int, EXCLUDE USING gist (lower(a) COLLATE public.c public.ops (x=1) DESC NULLS LAST WITH OPERATOR(public.&&), (b + 1) WITH <>) INCLUDE (b) WITH (fillfactor=80) USING INDEX TABLESPACE ts WHERE (b > 0) INITIALLY DEFERRED DEFERRABLE)",
    "CREATE TABLE t (a int, p int4range, UNIQUE (a, p WITHOUT OVERLAPS))",
    "CREATE TABLE t (a int, p int4range, PRIMARY KEY (a, p WITHOUT OVERLAPS) DEFERRABLE DEFERRABLE)",
    "CREATE TABLE t (a int, p int4range, FOREIGN KEY (a, PERIOD p) REFERENCES u (b, PERIOD q) NOT ENFORCED NOT VALID)",
    "CREATE TABLE t (a int, CHECK (a > 0) NOT VALID NO INHERIT ENFORCED)",
    "CREATE TABLE t (a int, NOT NULL a NOT VALID NO INHERIT)",
    "ALTER TABLE t ADD UNIQUE USING INDEX idx INITIALLY DEFERRED",
    "CREATE TABLE t (a int, UNIQUE USING INDEX idx)",
    "ALTER TABLE t ALTER CONSTRAINT c DEFERRABLE INITIALLY DEFERRED NOT ENFORCED NO INHERIT",
    "ALTER TABLE t ALTER CONSTRAINT c INHERIT",
    "ALTER TABLE t ALTER CONSTRAINT c",
    "ALTER TABLE t ALTER COLUMN a SET GENERATED BY DEFAULT SET INCREMENT BY 2 RESTART WITH 4 SET NO MAXVALUE",
    "ALTER TABLE t ALTER a RESTART SET CACHE 1.5 SET SEQUENCE NAME public.seq SET LOGGED",
    "ALTER TABLE t ALTER a ADD GENERATED ALWAYS AS IDENTITY (AS bigint RESTART 1 SEQUENCE NAME s)",
    "ALTER TABLE t ALTER a SET EXPRESSION AS (a + 1), ALTER b DROP EXPRESSION IF EXISTS",
    "ALTER TABLE ONLY (public.t) ALTER a RESET (n_distinct), SET ACCESS METHOD heap",
    "ALTER INDEX IF EXISTS idx SET (fillfactor=70), RESET (deduplicate_items)",
    "ALTER INDEX idx ALTER COLUMN 1 SET STATISTICS DEFAULT",
    "ALTER INDEX idx ATTACH PARTITION child",
    "ALTER VIEW v ALTER COLUMN a SET DEFAULT 1, SET (security_barrier=true)",
    "ALTER MATERIALIZED VIEW v SET ACCESS METHOD heap, SET TABLESPACE ts",
    "ALTER TABLE t REPLICA IDENTITY FULL",
    "ALTER TABLE t REPLICA IDENTITY DEFAULT",
    "ALTER TABLE t REPLICA IDENTITY NOTHING",
    "ALTER TABLE t REPLICA IDENTITY USING INDEX idx",
    "CREATE TABLE t (FOREIGN KEY (period) REFERENCES u (period))",
    "CREATE TABLE t (FOREIGN KEY (a, period) REFERENCES u (b, period))",
    "CREATE TABLE t (FOREIGN KEY (a, \"period\", PERIOD p) REFERENCES u (b, \"period\", PERIOD q))",
    "ALTER INDEX idx ALTER COLUMN 0x1 SET STATISTICS 1_000",
    "ALTER INDEX idx ALTER COLUMN 0o1 SET STATISTICS -1",
    "ALTER INDEX idx ALTER COLUMN 0b1 SET STATISTICS +10",
    "CREATE TABLE t (EXCLUDE (a WITH OPERATOR(=)) WITH (fillfactor))",
    "CREATE TABLE t (EXCLUDE (a WITH =) NOT DEFERRABLE INITIALLY IMMEDIATE)",
    "ALTER TABLE t ALTER a SET STORAGE DEFAULT",
    "ALTER TABLE t ALTER a SET STORAGE custom_mode",
    "ALTER INDEX i SET (select=1, namespace.where='x', reset)",
    "CREATE TABLE t (EXCLUDE (a WITH =) WITH (select=1, reset))",
    "CREATE TABLE t (UNIQUE (a) WITH (select=1, reset))",
    "ALTER TABLE t ALTER CONSTRAINT c DEFERRABLE DEFERRABLE NO INHERIT NO INHERIT",
    "ALTER TABLE t ALTER CONSTRAINT c INITIALLY IMMEDIATE NOT DEFERRABLE",
    "CREATE TABLE t (FOREIGN KEY (a) REFERENCES u ON DELETE SET NULL (a) ON UPDATE CASCADE)",
    "CREATE TABLE t OF public.tt",
    "CREATE TABLE t OF public.tt (a WITH OPTIONS DEFAULT 1, UNIQUE (a)) PARTITION BY RANGE (a)",
    "CREATE TABLE t PARTITION OF p (a WITH OPTIONS GENERATED ALWAYS AS (b + 1) STORED, CHECK (b > 0)) FOR VALUES FROM (1) TO (10)",
    "CREATE TABLE t PARTITION OF p (a) DEFAULT",
    "ALTER TABLE t OF public.tt",
    "ALTER TABLE t NOT OF",
    "CREATE TABLE t (EXCLUDE (CURRENT_DATE WITH =, CURRENT_USER WITH =, CURRENT_TIMESTAMP(2) WITH =))",
    "CREATE TABLE t (EXCLUDE (CAST(a AS int) WITH =, (f(a)::int) WITH =, ((f(a))[1]) WITH =))",
    "CREATE TABLE t (EXCLUDE ((sum(a) OVER ()) WITH =))",
    "CREATE TABLE t (EXCLUDE (COLLATION FOR (a) WITH =))"
};
static const char* const table_constraint_negative[] = {
    "ALTER VIEW t RENAME CONSTRAINT c TO d", "ALTER MATERIALIZED VIEW t RENAME CONSTRAINT c TO d",
    "CREATE TABLE t (EXCLUDE (f(a)::int WITH =))", "CREATE TABLE t (EXCLUDE (f(a)[1] WITH =))",
    "CREATE TABLE t (EXCLUDE (CURRENT_DATE::text WITH =))",
    "CREATE TABLE t (EXCLUDE (sum(a) OVER () WITH =))",
    "CREATE TABLE t (EXCLUDE (sum(a) FILTER (WHERE a > 0) WITH =))",
    "CREATE TABLE t (EXCLUDE (sum(a) WITHIN GROUP (ORDER BY a) WITH =))",
    "ALTER INDEX i SET SCHEMA s", "ALTER INDEX i RENAME COLUMN a TO b",
    "ALTER VIEW v ATTACH PARTITION t FOR VALUES IN (1)",
    "ALTER MATERIALIZED VIEW v DETACH PARTITION t", "ALTER INDEX i DETACH PARTITION t",
    "ALTER TABLE ONLY t * SET (x=1)",
    "CREATE TABLE t (EXCLUDE (a WITH =) WITH (namespace.where='x'))",
    "CREATE TABLE t (UNIQUE (a) WITH (namespace.where='x'))",
    "CREATE TABLE t OF tt ()", "CREATE TABLE t OF tt (a int)",
    "CREATE TABLE t OF tt INHERITS (u)", "CREATE TABLE t OF tt AS SELECT 1",
    "CREATE TABLE t PARTITION OF p (a int) DEFAULT",
    "CREATE TABLE t PARTITION OF p (a) DEFAULT INHERITS (u)",
    "CREATE TABLE t PARTITION OF p (LIKE u) DEFAULT",
    "ALTER TABLE t OF", "ALTER TABLE t NOT OF tt",
    "CREATE TABLE t (UNIQUE NULLS DISTINCT USING INDEX idx)",
    "CREATE TABLE t (EXCLUDE (a WITH =) WITH (a.b.c=1))",
    "ALTER INDEX i SET (a.b.c=1)",
    "ALTER TABLE t ALTER a RESTART 1, SET GENERATED ALWAYS",
    "ALTER TABLE t ALTER CONSTRAINT c ENFORCED NOT ENFORCED",
    "ALTER TABLE t ALTER CONSTRAINT c INITIALLY IMMEDIATE INITIALLY DEFERRED",
    "ALTER TABLE t REPLICA IDENTITY foo", "ALTER TABLE t REPLICA IDENTITY USING idx",
    "ALTER INDEX idx ALTER COLUMN 0x8000 SET STATISTICS 10",
    "CREATE TABLE t (FOREIGN KEY (a) REFERENCES u MATCH PARTIAL)",
    "CREATE TABLE t (FOREIGN KEY (a) REFERENCES u ON UPDATE SET NULL (a))",
    "CREATE TABLE t (EXCLUDE ())", "CREATE TABLE t (EXCLUDE (a))",
    "CREATE TABLE t (EXCLUDE (a WITH foo))", "CREATE TABLE t (EXCLUDE (a + 1 WITH =))",
    "CREATE TABLE t (EXCLUDE (a WITH =)) WHERE (a > 0)",
    "CREATE TABLE t (EXCLUDE (a WITH =) WHERE a > 0)",
    "CREATE TABLE t (EXCLUDE (a WITH =) NOT VALID)",
    "CREATE TABLE t (EXCLUDE (a WITH =) NOT ENFORCED)",
    "CREATE TABLE t (UNIQUE (a) NO INHERIT)",
    "CREATE TABLE t (UNIQUE (a) ENFORCED)",
    "CREATE TABLE t (UNIQUE (a) DEFERRABLE NOT DEFERRABLE)",
    "CREATE TABLE t (UNIQUE (a) NOT DEFERRABLE INITIALLY DEFERRED)",
    "CREATE TABLE t (CHECK (true) INITIALLY DEFERRED)",
    "CREATE TABLE t (CHECK (true) ENFORCED NOT ENFORCED)",
    "CREATE TABLE t (UNIQUE (a WITHOUT OVERLAPS, b))",
    "CREATE TABLE t (FOREIGN KEY (PERIOD p) REFERENCES u)",
    "CREATE TABLE t (FOREIGN KEY (a, PERIOD p, b) REFERENCES u)",
    "ALTER TABLE t ALTER CONSTRAINT c NOT VALID",
    "ALTER TABLE t ALTER CONSTRAINT c INHERIT DEFERRABLE",
    "ALTER TABLE t ALTER a SET GENERATED ALWAYS, RESTART 4",
    "ALTER TABLE t ALTER a SET RESTART 4",
    "ALTER TABLE t ALTER a SET AS bigint",
    "ALTER TABLE t ALTER a SET OWNED BY t.a",
    "ALTER TABLE t ALTER a RESTART WITH",
    "ALTER TABLE t ALTER a SET EXPRESSION AS a + 1",
    "ALTER INDEX i ALTER 0 SET STATISTICS 10",
    "ALTER INDEX i ALTER 32768 SET STATISTICS 10",
    "ALTER INDEX i ALTER 1 SET STATISTICS 2147483648",
    "ALTER TABLE t ADD a int, RENAME TO u",
    "ALTER TABLE t ADD a int, SET SCHEMA s",
    "ALTER TABLE t ATTACH PARTITION u FOR VALUES IN (1), ADD a int"
};
TEST(PgTableConstraints, NativeRoundTrips) {
    for (const char* sql : table_constraint_positive) {
        SCOPED_TRACE(sql);
        Parser<Dialect::PostgreSQL> parser; auto r = parser.parse(sql, std::strlen(sql));
        ASSERT_TRUE(r.ok() && r.full_input);
        Emitter<Dialect::PostgreSQL> emitter(parser.arena()); emitter.emit(r.ast); auto out = emitter.result();
        Parser<Dialect::PostgreSQL> again; auto rr = again.parse(out.ptr, out.len);
        EXPECT_TRUE(rr.ok() && rr.full_input) << std::string(out.ptr, out.len);
        EXPECT_FALSE(sql_engine::PlanBuilder<Dialect::PostgreSQL>::supports_query_features(r.ast));
        Arena dest; EXPECT_EQ(parameterize_ast<Dialect::PostgreSQL>(r, dest).error, AstError::UnsupportedRoot);
    }
}
TEST(PgTableConstraints, RejectsMalformed) {
    for (const char* sql : table_constraint_negative) {
        SCOPED_TRACE(sql); Parser<Dialect::PostgreSQL> parser; auto r=parser.parse(sql, std::strlen(sql));
        EXPECT_FALSE(r.ok() && r.full_input);
    }
}
TEST(PgTableConstraints, TraversalEditingAndArenaCompleteness) {
    const char* sql = table_constraint_positive[1];
    Parser<Dialect::PostgreSQL> baseline; auto r=baseline.parse(sql, std::strlen(sql));
    ASSERT_TRUE(r.ok() && r.full_input);
    size_t count=0; AstNode* literal=nullptr;
    walk_ast(r.ast, [&](const AstNode& n, const AstVisitContext&) {
        ++count; if(n.type==NodeType::NODE_LITERAL_INT && n.value()==StringRef{"0",1}) literal=const_cast<AstNode*>(&n);
        return AstVisitAction::Continue;
    });
    ASSERT_NE(literal, nullptr); literal->set_value({"9",1}); literal->set_source({});
    Emitter<Dialect::PostgreSQL> emitter(baseline.arena()); emitter.emit(r.ast); auto out=emitter.result();
    EXPECT_NE(std::string(out.ptr,out.len).find("b > 9"), std::string::npos);
    for(size_t capacity=48; capacity<=8192; capacity+=48) {
        ParserConfig cfg; cfg.arena_block_size=capacity; cfg.arena_max_size=capacity;
        Parser<Dialect::PostgreSQL> parser(cfg); auto rr=parser.parse(sql,std::strlen(sql));
        if(rr.ok() && rr.full_input) { size_t actual=0; walk_ast(rr.ast,[&](const AstNode&,const AstVisitContext&){++actual; return AstVisitAction::Continue;}); EXPECT_EQ(actual,count); }
    }
}

TEST(PgTableConstraints, AlterArenaCompleteness) {
    for (const char* sql : {table_constraint_positive[9], table_constraint_positive[12],
                           table_constraint_positive[17], table_constraint_positive[18]}) {
        Parser<Dialect::PostgreSQL> baseline; auto r=baseline.parse(sql,std::strlen(sql));
        ASSERT_TRUE(r.ok() && r.full_input); size_t expected=0;
        walk_ast(r.ast,[&](const AstNode&,const AstVisitContext&){++expected; return AstVisitAction::Continue;});
        for(size_t capacity=48;capacity<=4096;capacity+=48) {
            SCOPED_TRACE(sql);
            SCOPED_TRACE(capacity);
            ParserConfig cfg;cfg.arena_block_size=capacity;cfg.arena_max_size=capacity;
            Parser<Dialect::PostgreSQL> parser(cfg);auto rr=parser.parse(sql,std::strlen(sql));
            if(rr.ok() && rr.full_input) {size_t actual=0;walk_ast(rr.ast,[&](const AstNode&,const AstVisitContext&){++actual;return AstVisitAction::Continue;});EXPECT_EQ(actual,expected);}
        }
    }
}
