#ifndef SQL_PARSER_TOKEN_H
#define SQL_PARSER_TOKEN_H

#include "sql_parser/common.h"
#include <cstdint>

namespace sql_parser {

enum class TokenType : uint16_t {
    TK_EOF = 0,
    TK_ERROR,
    TK_IDENTIFIER,
    TK_INTEGER,
    TK_FLOAT,
    TK_STRING,
    TK_LPAREN,
    TK_RPAREN,
    TK_COMMA,
    TK_SEMICOLON,
    TK_DOT,
    TK_ASTERISK,
    TK_PLUS,
    TK_MINUS,
    TK_SLASH,
    TK_PERCENT,
    TK_EQUAL,
    TK_NOT_EQUAL,
    TK_LESS,
    TK_GREATER,
    TK_LESS_EQUAL,
    TK_GREATER_EQUAL,
    TK_AMPERSAND,
    TK_PIPE,
    TK_CARET,
    TK_TILDE,
    TK_EXCLAIM,
    TK_COLON,
    TK_QUESTION,
    TK_AT,
    TK_DOUBLE_AT,
    TK_HASH,
    TK_COLON_EQUAL,
    TK_DOUBLE_PIPE,
    TK_DOUBLE_COLON,
    TK_DOLLAR_NUM,
    TK_SELECT, TK_INSERT, TK_UPDATE, TK_DELETE, TK_REPLACE,
    TK_FROM, TK_WHERE, TK_SET, TK_INTO, TK_VALUES, TK_AS, TK_ON, TK_USING,
    TK_JOIN, TK_INNER, TK_LEFT, TK_RIGHT, TK_FULL, TK_OUTER, TK_CROSS, TK_NATURAL,
    TK_ORDER, TK_BY, TK_GROUP, TK_HAVING, TK_LIMIT, TK_OFFSET, TK_FETCH,
    TK_ASC, TK_DESC, TK_DISTINCT, TK_ALL,
    TK_AND, TK_OR, TK_NOT, TK_IS, TK_NULL, TK_IN, TK_BETWEEN, TK_LIKE, TK_EXISTS,
    TK_CASE, TK_WHEN, TK_THEN, TK_ELSE, TK_END, TK_TRUE, TK_FALSE,
    TK_NAMES, TK_CHARACTER, TK_CHARSET, TK_COLLATE, TK_GLOBAL, TK_SESSION, TK_LOCAL,
    TK_PERSIST, TK_DEFAULT, TK_TRANSACTION, TK_ISOLATION, TK_LEVEL,
    TK_READ, TK_WRITE, TK_ONLY, TK_COMMITTED, TK_UNCOMMITTED, TK_REPEATABLE,
    TK_SERIALIZABLE, TK_TO,
    TK_CREATE, TK_ALTER, TK_DROP, TK_TRUNCATE, TK_TABLE, TK_INDEX, TK_VIEW,
    TK_DATABASE, TK_SCHEMA, TK_IF,
    TK_BEGIN, TK_START, TK_COMMIT, TK_ROLLBACK, TK_SAVEPOINT,
    TK_USE, TK_SHOW, TK_PREPARE, TK_EXECUTE, TK_DEALLOCATE,
    TK_GRANT, TK_REVOKE, TK_LOCK, TK_UNLOCK, TK_LOAD, TK_DATA,
    TK_FOR, TK_SHARE, TK_NOWAIT, TK_SKIP, TK_LOCKED,
    TK_OUTFILE, TK_DUMPFILE, TK_IGNORE, TK_LOW_PRIORITY, TK_QUICK, TK_RESET,
    TK_UNION, TK_OF,
    TK_SQL_CALC_FOUND_ROWS,
    TK_COUNT, TK_SUM, TK_AVG, TK_MIN, TK_MAX,
};

struct Token {
    TokenType type = TokenType::TK_EOF;
    StringRef text;
    uint32_t offset = 0;
};

} // namespace sql_parser

#endif // SQL_PARSER_TOKEN_H
